//! Catalog: table definitions, built-in objects and the read-only view the
//! analyzer and planner use.

pub mod builtin;
pub mod cache;
pub mod check;
pub mod depend;
#[cfg(test)]
pub(crate) mod fake;
pub mod names;
pub mod naming;
pub mod opclass;
pub mod reader;
pub mod rows;
pub mod schema;
pub mod seq_params;
pub mod store;

use std::sync::Arc;

pub use builtin::{
    BuiltinCast, BuiltinFunction, BuiltinOperator, BuiltinType, CastContext, CastMethod,
};

use crate::error::Result;
use crate::executor::{RuntimeInfo, SessionInfo};
use crate::storage::smgr::RelFileLocator;
use crate::types::ops::BuiltinFn;
use crate::types::{Datum, Oid, SqlType, oid};

/// Source text of a stored expression (DEFAULT). It is parsed and analyzed
/// again every time it is used.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BoundExprSource {
    pub expr_sql: String,
}

/// `pg_attribute.attidentity`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum IdentityKind {
    /// `a`: `GENERATED ALWAYS AS IDENTITY`.
    Always,
    /// `d`: `GENERATED BY DEFAULT AS IDENTITY`.
    ByDefault,
}

impl IdentityKind {
    /// The `attidentity` character.
    pub fn code(self) -> char {
        match self {
            IdentityKind::Always => 'a',
            IdentityKind::ByDefault => 'd',
        }
    }

    pub fn from_code(c: char) -> Option<IdentityKind> {
        match c {
            'a' => Some(IdentityKind::Always),
            'd' => Some(IdentityKind::ByDefault),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ColumnDef {
    pub name: String,
    /// 1-based.
    pub attnum: i16,
    pub ty: SqlType,
    pub not_null: bool,
    pub default: Option<BoundExprSource>,
    /// `attidentity`（M4。`None` = 通常の列）。
    pub identity: Option<IdentityKind>,
}

/// A CHECK constraint, stored as SQL text of its expression.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CheckDef {
    pub name: String,
    pub expr_sql: String,
    /// `NO INHERIT`（`pg_constraint.connoinherit`）。
    pub no_inherit: bool,
}

/// `pg_class.relkind`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum RelKind {
    /// `r`.
    Table,
    /// `i`（M4）。`CatalogReader::table()` は返さない。
    Index,
    /// `S`（M4）。列とヒープを持ち SELECT できる。
    Sequence,
}

impl RelKind {
    /// The `relkind` character: `r` / `i` / `S`.
    pub fn code(self) -> char {
        match self {
            RelKind::Table => 'r',
            RelKind::Index => 'i',
            RelKind::Sequence => 'S',
        }
    }

    pub fn from_code(c: char) -> Option<RelKind> {
        match c {
            'r' => Some(RelKind::Table),
            'i' => Some(RelKind::Index),
            'S' => Some(RelKind::Sequence),
            _ => None,
        }
    }

    /// The noun used in error messages: `table` / `index` / `sequence`.
    pub fn noun(self) -> &'static str {
        match self {
            RelKind::Table => "table",
            RelKind::Index => "index",
            RelKind::Sequence => "sequence",
        }
    }
}

/// `pg_constraint.contype`（M4 は c / p / u だけ）。
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ConstraintKind {
    /// `c`.
    Check,
    /// `p`.
    PrimaryKey,
    /// `u`.
    Unique,
}

/// `pg_constraint` の 1 行。`pg_get_constraintdef` と DROP の説明が使う。
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConstraintDef {
    pub oid: Oid,
    pub name: String,
    pub namespace: Oid,
    pub kind: ConstraintKind,
    pub table_oid: Oid,
    /// PRIMARY KEY / UNIQUE の索引（`conindid`）。Check は `None`。
    pub index_oid: Option<Oid>,
    /// `conkey`（attnum の並び）。Check は空。
    pub columns: Vec<i16>,
    /// Check の式（`conbin`。SQL テキスト）。
    pub check_sql: Option<String>,
    /// `connoinherit`（CHECK の `NO INHERIT`）。
    pub no_inherit: bool,
}

/// 索引のキー列 1 つ（INCLUDE・式・部分索引は M4 にない）。
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IndexColumn {
    pub attnum: i16,
    pub opclass: Oid,
    pub opfamily: Oid,
    pub descending: bool,
    pub nulls_first: bool,
}

/// PRIMARY KEY / UNIQUE 制約が索引を所有するときの、その制約。
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IndexConstraintRef {
    pub oid: Oid,
    pub name: String,
}

/// A B+Tree index definition (`pg_class` + `pg_index`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IndexDef {
    pub oid: Oid,
    pub name: String,
    pub namespace: Oid,
    pub table_oid: Oid,
    pub locator: RelFileLocator,
    pub columns: Vec<IndexColumn>,
    pub unique: bool,
    pub primary: bool,
    pub constraint: Option<IndexConstraintRef>,
}

impl IndexDef {
    /// PRIMARY KEY / UNIQUE 制約が所有する索引か。
    pub fn is_constraint_index(&self) -> bool {
        self.constraint.is_some()
    }

    /// 列 `i` の `indoption`（bit0 = DESC、bit1 = NULLS FIRST）。範囲外は 0。
    pub fn indoption(&self, i: usize) -> i16 {
        self.columns.get(i).map_or(0, |c| {
            i16::from(c.descending) | (i16::from(c.nulls_first) << 1)
        })
    }

    /// `indoption` から `(descending, nulls_first)` を復元する。
    pub fn flags_from_indoption(v: i16) -> (bool, bool) {
        (v & 1 != 0, v & 2 != 0)
    }
}

/// シーケンスのパラメータ（`pg_sequence`）。
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SequenceParams {
    /// int2 / int4 / int8.
    pub type_oid: Oid,
    pub start: i64,
    pub increment: i64,
    pub min: i64,
    pub max: i64,
    pub cache: i64,
    pub cycle: bool,
    /// `OWNED BY`: (表の OID, attnum).
    pub owned_by: Option<(Oid, i16)>,
}

/// An immutable table definition. Shared via `Arc`; DDL replaces the whole
/// `Arc<TableDef>`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TableDef {
    pub oid: Oid,
    /// `pg_class.relnamespace`: 11 = `pg_catalog`, 2200 = `public`.
    pub namespace: Oid,
    pub schema: String,
    pub name: String,
    pub kind: RelKind,
    /// Where the table's main fork lives.
    pub locator: RelFileLocator,
    pub columns: Vec<ColumnDef>,
    pub checks: Vec<CheckDef>,
    /// 索引（OID 昇順）。`kind = Table` のときだけ。
    pub indexes: Vec<Arc<IndexDef>>,
    /// `kind = Sequence` のときだけ。
    pub sequence: Option<SequenceParams>,
    /// IDENTITY 列と暗黙のシーケンスの対応: (attnum, シーケンスの OID)。
    pub identity_seqs: Vec<(i16, Oid)>,
}

impl TableDef {
    /// Tables created by initdb (OID below 16384).
    pub fn is_system_catalog(&self) -> bool {
        self.oid < oid::FIRST_NORMAL_OBJECT_ID
    }

    /// Finds a column by (already case-folded) name.
    pub fn column(&self, name: &str) -> Option<&ColumnDef> {
        self.columns.iter().find(|c| c.name == name)
    }

    /// 0-based index of a column by name.
    pub fn column_index(&self, name: &str) -> Option<usize> {
        self.columns.iter().position(|c| c.name == name)
    }

    /// The PRIMARY KEY index, if any.
    pub fn primary_key(&self) -> Option<&Arc<IndexDef>> {
        self.indexes.iter().find(|i| i.primary)
    }

    pub fn index_by_oid(&self, oid: Oid) -> Option<&Arc<IndexDef>> {
        self.indexes.iter().find(|i| i.oid == oid)
    }

    pub fn index_by_name(&self, name: &str) -> Option<&Arc<IndexDef>> {
        self.indexes.iter().find(|i| i.name == name)
    }
}

/// 集約関数の種類（`m4/00-contracts.md` §11.3）。
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum AggKind {
    CountStar,
    Count,
    SumInt2,
    SumInt4,
    SumInt8,
    SumFloat4,
    SumFloat8,
    SumNumeric,
    AvgInt2,
    AvgInt4,
    AvgInt8,
    AvgFloat4,
    AvgFloat8,
    AvgNumeric,
    /// 引数の型の比較で動く（型ごとに `BuiltinAggregate` の行がある）。
    Min,
    Max,
    /// `every` は `BoolAnd` の別名の行。
    BoolAnd,
    BoolOr,
    /// `string_agg(text, text)`。区切りが NULL なら空文字列。
    StringAgg,
}

/// A row of `pg_proc` with `prokind = 'a'`.
#[derive(Debug)]
pub struct BuiltinAggregate {
    /// `pg_proc.oid`.
    pub oid: Oid,
    pub name: &'static str,
    /// `count(*)` は空。
    pub args: &'static [Oid],
    pub result: Oid,
    pub kind: AggKind,
}

/// Read-only view of the catalog used by the analyzer and planner.
///
/// The table lookups and the session-related methods must be provided; the
/// built-in lookups default to the static tables in `builtin` (`m2.md` §6.8.5).
pub trait CatalogReader: std::fmt::Debug {
    /// Looks up a table. `schema = None` means "search the `search_path`"
    /// (`pg_catalog` is implicitly first). Errors are I/O or checksum
    /// failures while reading the catalog tables.
    fn table(&self, schema: Option<&str>, name: &str) -> Result<Option<Arc<TableDef>>>;

    fn table_by_oid(&self, oid: Oid) -> Result<Option<Arc<TableDef>>>;

    fn current_database(&self) -> &str;

    /// The effective `search_path` entries (`"$user"`, `public`, ...).
    fn search_path(&self) -> &[String];

    /// `pg_get_userbyid`: the role name for a role OID.
    fn role_name(&self, oid: Oid) -> Result<Option<String>>;

    /// `pg_table_is_visible`: OIDs of the namespaces on the resolved
    /// `search_path` (`pg_catalog` first).
    fn visible_namespaces(&self) -> Result<Vec<Oid>>;

    /// 表・インデックス・シーケンスのどれでも（名前空間は共有）。DDL の名前衝突、DROP INDEX、
    /// regclass の入力、42809 の判定に使う。既定は「見つからない」（C1 が上書きする）。
    fn relation_kind(&self, _schema: Option<&str>, _name: &str) -> Result<Option<(Oid, RelKind)>> {
        Ok(None)
    }

    fn index_by_name(&self, _schema: Option<&str>, _name: &str) -> Result<Option<Arc<IndexDef>>> {
        Ok(None)
    }

    fn index_by_oid(&self, _oid: Oid) -> Result<Option<Arc<IndexDef>>> {
        Ok(None)
    }

    /// regclass の出力用。検索パスで見える名前空間なら修飾しない（`regclassout` と同じ）。
    fn relation_name(&self, _oid: Oid) -> Result<Option<String>> {
        Ok(None)
    }

    /// `pg_constraint` の 1 行（c / p / u）。`pg_get_constraintdef` が使う。
    fn constraint_by_oid(&self, _oid: Oid) -> Result<Option<ConstraintDef>> {
        Ok(None)
    }

    /// 集約関数。既定は静的な表。
    fn aggregates_named(&self, name: &str) -> Vec<&'static BuiltinAggregate> {
        builtin::aggregates_named(name)
    }

    fn type_by_oid(&self, oid: Oid) -> Option<&'static BuiltinType> {
        builtin::type_by_oid(oid)
    }

    /// Looks up a type by its `pg_type.typname` (e.g. `int4`, `varchar`).
    /// SQL-standard spellings (`integer`, `character varying`) are
    /// normalized by the parser, as in PostgreSQL's grammar.
    fn type_by_name(&self, name: &str) -> Option<&'static BuiltinType> {
        builtin::type_by_name(name)
    }

    /// The cast from `source` to `target`, if one exists in `pg_cast`.
    /// (Contract 3.3 allows this form instead of `casts_from`.)
    fn find_cast(&self, source: Oid, target: Oid) -> Option<&'static BuiltinCast> {
        builtin::find_cast(source, target)
    }

    fn operators_named(&self, name: &str) -> Vec<&'static BuiltinOperator> {
        builtin::operators_named(name)
    }

    fn functions_named(&self, name: &str) -> Vec<&'static BuiltinFunction> {
        builtin::functions_named(name)
    }
}

/// System columns a SELECT / UPDATE / DELETE may reference (`m2.md` §4.6).
/// Shared by the analyzer and the planner.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum SystemColumn {
    Ctid,
    Xmin,
    Cmin,
    Xmax,
    Cmax,
    TableOid,
}

/// How a built-in function is implemented (`m2.md` §4.6).
#[derive(Clone, Copy)]
pub enum FnKind {
    /// Depends on the arguments only (the M1 form).
    Pure(BuiltinFn),
    /// Uses the catalog or session (`pg_get_userbyid`, `pg_table_is_visible`,
    /// `format_type`, ...).
    Context(fn(&[Datum], &dyn CatalogReader, &SessionInfo) -> Result<Datum>),
    /// 実行時の情報を使う（`pg_backend_pid`、`pg_sleep`、`pg_isolation_test_session_is_blocked`。`m3.md` §4.9）。
    Runtime(fn(&[Datum], &dyn RuntimeInfo) -> Result<Datum>),
    /// FROM 句でだけ呼べる集合返却関数（`generate_series`。`m4/09-types-functions.md` §10.1）。
    Set(SetFn),
}

/// 集合返却関数の実装。
#[derive(Clone, Copy)]
pub struct SetFn {
    /// 引数（評価済み）から行の生成器を作る。引数に NULL があれば 0 行（strict）。
    pub begin: fn(&[Datum]) -> Result<Box<dyn SetIter>>,
    /// `FROM generate_series(..)` の列名と別名の既定（`generate_series`）。
    pub column_name: &'static str,
}

impl std::fmt::Debug for SetFn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SetFn")
            .field("column_name", &self.column_name)
            .finish_non_exhaustive()
    }
}

/// `SetFn::begin` が返す行の生成器。
pub trait SetIter {
    /// 次の値。尽きたら `None`。
    fn next(&mut self) -> Result<Option<Datum>>;
}

impl std::fmt::Debug for FnKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FnKind::Pure(_) => f.write_str("FnKind::Pure(..)"),
            FnKind::Context(_) => f.write_str("FnKind::Context(..)"),
            FnKind::Runtime(_) => f.write_str("FnKind::Runtime(..)"),
            FnKind::Set(s) => write!(f, "FnKind::Set({s:?})"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn relkind_and_identity_codes() {
        for (k, c, noun) in [
            (RelKind::Table, 'r', "table"),
            (RelKind::Index, 'i', "index"),
            (RelKind::Sequence, 'S', "sequence"),
        ] {
            assert_eq!(k.code(), c);
            assert_eq!(RelKind::from_code(c), Some(k));
            assert_eq!(k.noun(), noun);
        }
        assert_eq!(RelKind::from_code('v'), None);
        assert_eq!(IdentityKind::from_code('a'), Some(IdentityKind::Always));
        assert_eq!(IdentityKind::ByDefault.code(), 'd');
        assert_eq!(IdentityKind::from_code(' '), None);
    }

    #[test]
    fn index_options_round_trip() {
        let col = |descending, nulls_first| IndexColumn {
            attnum: 1,
            opclass: 0,
            opfamily: 0,
            descending,
            nulls_first,
        };
        let def = IndexDef {
            oid: 1,
            name: "i".into(),
            namespace: 2200,
            table_oid: 2,
            locator: crate::storage::smgr::RelFileLocator {
                spc_oid: 1663,
                db_oid: 5,
                rel_number: crate::storage::smgr::RelFileNumber(1),
            },
            columns: vec![
                col(false, false),
                col(true, false),
                col(false, true),
                col(true, true),
            ],
            unique: false,
            primary: false,
            constraint: None,
        };
        for (i, want) in [0i16, 1, 2, 3].into_iter().enumerate() {
            assert_eq!(def.indoption(i), want);
            let (d, n) = IndexDef::flags_from_indoption(want);
            assert_eq!(
                (d, n),
                (def.columns[i].descending, def.columns[i].nulls_first)
            );
        }
        assert_eq!(def.indoption(9), 0);
        assert!(!def.is_constraint_index());
    }

    #[test]
    fn catalog_reader_defaults_are_empty() {
        let c = fake::FakeCatalog::new("postgres");
        // FakeCatalog が上書きしない既定: 制約なし、集約は静的な表。
        assert!(c.constraint_by_oid(1).unwrap().is_none());
        assert!(!builtin::aggregates_named("count").is_empty());
        assert!(!builtin::AGGREGATES.is_empty());
    }
}
