//! Differential test against PostgreSQL 17: every case in
//! `fixtures/pg17_corpus.tsv` (generated by `fixtures/gen_corpus.py` from a
//! real server) must produce exactly the same text or error.

use std::path::PathBuf;

use yuzhu_datetime::{
    Date, DateOrder, DateStyle, DateTimeEnv, DateTimeError, FsZoneSource, Interval, Timestamp,
    TimestampTz, ZoneDb, date_part_date, date_part_interval, date_part_timestamp,
    date_part_timestamptz, date_trunc_interval, date_trunc_timestamp, date_trunc_timestamptz,
    extract_date, extract_interval, extract_timestamp, extract_timestamptz, format_float8,
    interval_range, interval_typmod, parse_datestyle, parse_intervalstyle, parse_timezone_setting,
};

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

type Res = Result<String, DateTimeError>;

fn err_text(e: &DateTimeError) -> String {
    format!("ERROR {} {}", e.sqlstate, e.message)
}

fn opt_num(v: Option<yuzhu_datetime::NumericValue>) -> String {
    v.map_or_else(|| "NULL".to_owned(), |n| n.to_string())
}

fn opt_f64(v: Option<f64>) -> String {
    v.map_or_else(|| "NULL".to_owned(), format_float8)
}

fn parse_float(s: &str) -> f64 {
    let s = s.trim_matches('\'');
    match s {
        "Infinity" => f64::INFINITY,
        "-Infinity" => f64::NEG_INFINITY,
        "NaN" => f64::NAN,
        _ => s.parse().expect("float"),
    }
}

/// Map the interval typmod suffixes used by the generator to typmods.
fn interval_suffix_typmod(s: &str) -> i32 {
    use interval_range::{DAY, FULL, HOUR, MINUTE, MONTH, SECOND, YEAR};
    let s = s.trim();
    let (fields, prec) = match s.find('(') {
        Some(i) => (
            s[..i].trim(),
            Some(s[i + 1..s.len() - 1].parse::<i32>().expect("precision")),
        ),
        None => (s, None),
    };
    let range = match fields {
        "" => FULL,
        "year" => YEAR,
        "month" => MONTH,
        "day" => DAY,
        "hour" => HOUR,
        "minute" => MINUTE,
        "second" => SECOND,
        "year to month" => YEAR | MONTH,
        "day to hour" => DAY | HOUR,
        "day to minute" => DAY | HOUR | MINUTE,
        "day to second" => DAY | HOUR | MINUTE | SECOND,
        "hour to minute" => HOUR | MINUTE,
        "hour to second" => HOUR | MINUTE | SECOND,
        "minute to second" => MINUTE | SECOND,
        other => panic!("unknown interval fields {other:?}"),
    };
    interval_typmod(prec, range)
}

#[allow(clippy::too_many_lines)]
fn eval(kind: &str, a: &str, b: &str, env: &DateTimeEnv<'_>, zones: &ZoneDb) -> Res {
    let tz = env.time_zone;
    let ist = env.interval_style;
    let ts = |s: &str| Timestamp::parse(s, -1, env);
    let tstz = |s: &str| TimestampTz::parse(s, -1, env);
    let date = |s: &str| Date::parse(s, env);
    let iv = |s: &str| Interval::parse(s, -1, env);
    Ok(match kind {
        "date_in" => date(a)?.format(env),
        "ts_in" => ts(a)?.format(env)?,
        "tstz_in" => tstz(a)?.format(env)?,
        "iv_in" => iv(a)?.format(ist),
        "ts_typmod" => Timestamp::parse(a, b.parse().unwrap(), env)?.format(env)?,
        "tstz_typmod" => TimestampTz::parse(a, b.parse().unwrap(), env)?.format(env)?,
        "iv_typmod" => Interval::parse(a, interval_suffix_typmod(b), env)?.format(ist),
        "ts_pl_iv" => ts(a)?.add_interval(&iv(b)?)?.format(env)?,
        "ts_mi_iv" => ts(a)?.sub_interval(&iv(b)?)?.format(env)?,
        "tstz_pl_iv" => tstz(a)?.add_interval(&iv(b)?, tz)?.format(env)?,
        "tstz_mi_iv" => tstz(a)?.sub_interval(&iv(b)?, tz)?.format(env)?,
        "ts_mi_ts" => ts(a)?.sub_timestamp(ts(b)?)?.format(ist),
        "tstz_mi_tstz" => tstz(a)?.sub_timestamptz(tstz(b)?)?.format(ist),
        "date_pl_int" => date(a)?.add_days(b.parse().unwrap())?.format(env),
        "date_mi_int" => date(a)?.sub_days(b.parse().unwrap())?.format(env),
        "date_mi_date" => {
            let (x, y) = (date(a)?, date(b)?);
            x.sub_date(y)?.to_string()
        }
        "date_pl_iv" => date(a)?.add_interval(&iv(b)?)?.format(env)?,
        "date_mi_iv" => date(a)?.sub_interval(&iv(b)?)?.format(env)?,
        "iv_pl_iv" => iv(a)?.add(&iv(b)?)?.format(ist),
        "iv_mi_iv" => iv(a)?.sub(&iv(b)?)?.format(ist),
        "iv_mul" => iv(a)?.mul(parse_float(b))?.format(ist),
        "iv_div" => iv(a)?.div(parse_float(b))?.format(ist),
        "iv_neg" => iv(a)?.negate()?.format(ist),
        "iv_cmp" => {
            let (x, y) = (iv(a)?, iv(b)?);
            match x.cmp(&y) {
                std::cmp::Ordering::Less => "-1",
                std::cmp::Ordering::Equal => "0",
                std::cmp::Ordering::Greater => "1",
            }
            .to_owned()
        }
        "justify_hours" => iv(a)?.justify_hours()?.format(ist),
        "justify_days" => iv(a)?.justify_days()?.format(ist),
        "justify_interval" => iv(a)?.justify_interval()?.format(ist),
        "ts_to_tstz" => ts(a)?.to_timestamptz(tz)?.format(env)?,
        "tstz_to_ts" => tstz(a)?.to_timestamp(tz)?.format(env)?,
        "date_to_tstz" => date(a)?.to_timestamptz(tz)?.format(env)?,
        "tstz_to_date" => tstz(a)?.to_date(tz)?.format(env),
        "ts_to_date" => ts(a)?.to_date()?.format(env),
        "date_to_ts" => date(a)?.to_timestamp()?.format(env)?,
        "extract_ts" => opt_num(extract_timestamp(b, ts(a)?)?),
        "extract_tstz" => opt_num(extract_timestamptz(b, tstz(a)?, tz)?),
        "extract_iv" => opt_num(extract_interval(b, &iv(a)?)?),
        "extract_date" => opt_num(extract_date(b, date(a)?)?),
        "part_ts" => opt_f64(date_part_timestamp(b, ts(a)?)?),
        "part_tstz" => opt_f64(date_part_timestamptz(b, tstz(a)?, tz)?),
        "part_iv" => opt_f64(date_part_interval(b, &iv(a)?)?),
        "part_date" => opt_f64(date_part_date(b, date(a)?)?),
        "trunc_ts" => date_trunc_timestamp(b, ts(a)?)?.format(env)?,
        "trunc_tstz" => date_trunc_timestamptz(b, tstz(a)?, tz)?.format(env)?,
        "trunc_iv" => date_trunc_interval(b, &iv(a)?)?.format(ist),
        "ts_at_tz" => ts(a)?.at_time_zone(b, env)?.format(env)?,
        "tstz_at_tz" => tstz(a)?.at_time_zone(b, env)?.format(env)?,
        "tstz_roundtrip" => tstz(&tstz(a)?.format(env)?)?.format(env)?,
        "ts_roundtrip" => ts(&ts(a)?.format(env)?)?.format(env)?,
        "date_roundtrip" => date(&date(a)?.format(env))?.format(env),
        "iv_roundtrip" => iv(&iv(a)?.format(ist))?.format(ist),
        "set_tz" => {
            let z = parse_timezone_setting(zones, a)?;
            let probe = TimestampTz::parse("2024-07-01 12:00:00+00", -1, env)?;
            let env2 = DateTimeEnv {
                time_zone: &z,
                ..*env
            };
            format!("{} {}", z.name(), probe.format(&env2)?)
        }
        other => panic!("unknown kind {other}"),
    })
}

#[test]
fn matches_postgresql_17() {
    let text = std::fs::read_to_string(fixtures().join("pg17_corpus.tsv")).expect("corpus");
    let zones = ZoneDb::new(Box::new(FsZoneSource::new(fixtures().join("zoneinfo"))));
    let mut total = 0usize;
    let mut failures: Vec<String> = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let cols: Vec<&str> = line.split('\t').collect();
        assert_eq!(cols.len(), 7, "bad line: {line}");
        let (kind, tzname, ds, ist, a, b, expected) = (
            cols[0], cols[1], cols[2], cols[3], cols[4], cols[5], cols[6],
        );
        total += 1;
        let tz = parse_timezone_setting(&zones, tzname).expect("zone setting");
        let (date_style, date_order) =
            parse_datestyle(ds, (DateStyle::default(), DateOrder::default())).expect("datestyle");
        let env = DateTimeEnv {
            date_style,
            date_order,
            interval_style: parse_intervalstyle(ist).expect("intervalstyle"),
            time_zone: &tz,
            zones: &zones,
            now: TimestampTz(0),
        };
        let got = match eval(kind, a, b, &env, &zones) {
            Ok(s) => s,
            Err(e) => err_text(&e),
        };
        if got != expected {
            failures.push(format!(
                "{kind} [{tzname} | {ds} | {ist}] a={a:?} b={b:?}\n    expected: {expected}\n    got:      {got}"
            ));
        }
    }
    let shown: Vec<&str> = failures.iter().take(80).map(String::as_str).collect();
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from PostgreSQL 17:\n{}",
        failures.len(),
        total,
        shown.join("\n")
    );
    assert!(total > 50_000, "corpus unexpectedly small: {total}");
}
